### ISSUE TITLE
Not working in node v0.8.16

### ISSUE THREAD

**Issue by fulmicoton** [nlf/markitup#6]
Markitup fails on node 0.8.16 with the following error message.

/data/masurel/opt/node/lib/node_modules/markitup/node_modules/marked/lib/marked.js:521
    throw new
          ^
Error: Tokens array requires a `links` property.
    at new InlineLexer (/data/masurel/opt/node/lib/node_modules/markitup/node_modules/marked/lib/marked.js:521:11)
    at Parser.parse (/data/masurel/opt/node/lib/node_modules/markitup/node_modules/marked/lib/marked.js:773:17)
    at Function.Parser.parse [as parser](/data/masurel/opt/node/lib/node_modules/markitup/node_modules/marked/lib/marked.js:765:17)
    at marked (/data/masurel/opt/node/lib/node_modules/markitup/lib/parser.js:39:20)
    at write_html (/data/masurel/opt/node/lib/node_modules/markitup/lib/markitup.js:42:42)
    at Object.exports.generate_doc (/data/masurel/opt/node/lib/node_modules/markitup/lib/markitup.js:18:5)
    at /data/masurel/opt/node/lib/node_modules/markitup/bin/markitup:37:30
    at Object.oncomplete (fs.js:297:15)

**Comment by nlf** [comment]
At first glance, looks like that may be an issue with marked. I'll look in to updating

**Comment by nlf** [comment]
This is fixed in 0.0.8

**Comment by fulmicoton** [comment]
Thank you!
